FROM &&OS&&:&&DIST&&

ADD php-compiler.sh /root/
RUN chmod +x /root/php-compiler.sh
RUN bash /root/php-compiler.sh "&&PHPVL&&"

RUN /etc/init.d/&&PHPVS&&-fpm start

RUN /bin/bash -c "source /etc/profile.d/&&PHPVS&&-alias.sh; &&PHPVS&& -v"
